version: '3.9'

services:
  website:
    build:
      context: ./apps/website
      dockerfile: Dockerfile
    container_name: web
    restart: 'always'
    volumes:
      - ./apps/website:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
